### ISSUE TITLE
[BUG] Various Bugs

### ISSUE THREAD

**Issue by rogodra** [ngocjohn/sidebar-organizer#6]
Hi, thanks for this plugin.

I'll describe several bugs I've encountered using the plugin.

1. Already reported. There's no way to create a new group. The option doesn't appear.

2. I'm using the Use yaml file option, since I don't have the option to create groups.
If a new Dashboards is added and entered into the yaml file, it goes into a bootloop. Deleting cookies then works fine.

3. I use Firefox and it works fine, but for some reason it doesn't work in Edge, although it does in a private window. Tried deleting cookies, but no solution.

**Comment by ngocjohn** [comment]
Hi @rogodra, there's a new beta release with fixes for these bugs. Can you please try it?

**Comment by rogodra** [comment]
Hi @ngocjohn,

I've been testing the new beta. I'll share the results.

1. Fixed, it now allows you to create groups, but there's a new bug: when you save the configuration, the entire sidebar is blank, without any icons.

2. The problem with adding a new Dashboards persists.

3. It's now functional with Edge, although it has the same issues mentioned above.

**Comment by ngocjohn** [comment]
Hi @rogodra, items in the sidebar is more complicated than a regular lovelace card. Because it is created when the component is connected to the page, it has not fixed base config. I recommend to doing changes with UI mode, yaml mode is used for synchronization with another device. Because the popup config dialog will always update the newer data first, whether it is a new item added or an item added to hidden. Compare the dialog with the user config and if the fields in the custom are different from the sidebar panels, it will be deleted. 

I don't know if you already have major changes, but you can try to create a completely new groups with items, this way you get a refresh from the old version where I had major bugs.

**Comment by rogodra** [comment]
Hi @ngocjohn 

With the beta version, if I do the UI configuration, it breaks completely. Everything is blank.

Tested in Firefox and Edge, and with a private window.

![Image](https://github.com/user-attachments/assets/1566b98f-aff9-4a10-8ebd-99867f710390)

**Comment by ngocjohn** [comment]
Can you insert your config here? from yaml?

**Comment by rogodra** [comment]
Yes, the editor displays correctly. However, any configuration made through the UI causes the sidebar to be left without any icons.

![Image](https://github.com/user-attachments/assets/53eba4f2-167d-4801-b7ad-628a16dc859f)

From the sidebar-organizer.yaml file, everything works correctly. The only issue is that if a new Dashboard is added, it goes into a boot loop; this is resolved by deleting the cookies.

Code from sidebar-organizer.yaml

```
bottom_items:
  - alarmo
custom_groups:
  panells:
    - panel1
  apps:
    - hacs
    - 5c53de3b_esphome
    - 45df7312_zigbee2mqtt
  media:
    - d5369777_music_assistant
    - media-browser
    - calendar
  addons:
    - a0d7b954_vscode
    - a0d7b954_adguard
  registres:
    - logbook
    - history
    - energy
    - map
default_collapsed:
  - addons
  - registres
```
